apiVersion: skaffold/v3
kind: Config
deploy:
  kubectl:
    remoteManifests:
      - ./infra/k8s/*
metadata:
  name: auth-micro
build:
  artifacts:
    - image: mkd/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "server/**/*.ts"
            dest: .
    - image: mkd/test-kafka
      context: test-kafka
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

manifests:
  rawYaml:
    - ./infra/k8s/*
