apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: auth-micro
build:
  artifacts:
  - image: mkd/auth
    context: auth
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - infra/k8s/auth-depl.yaml
  - infra/k8s/ingress-depl.yaml
  - infra/k8s/kafka-depl.yaml
  - infra/k8s/zookeeper-depl.yaml
  - infra/namespace/kafka-namespace.yaml
  - infra/namespace/kafka-test.yaml
  - infra/namespace/zookeeper-test.yaml
