apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: zookeeper:latest
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          imagePullPolicy: IfNotPresent
          name: zookeeper-depl
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-srv
spec:
  type: NodePort
  ports:
    - name: zookeeper
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: zookeeper
