apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-srv:2181
            - name: KAFKA_CFG_LISTENERS
              value: CLIENT://:9092,EXTERNAL://:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: CLIENT://kafka-srv:9092,EXTERNAL://localhost:9093
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: CLIENT
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          name: kafka
          ports:
            - containerPort: 9092
            - '9092:9092'
            - '9093:9093'

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
